#ifndef __FUNCTION_CODE_H__
#define __FUNCTION_CODE_H__

#define FC_READ_COILS               0x01
#define FC_READ_DISCRETE_INPUTS     0x02
#define FC_READ_HOLDING_REGISTERS   0x03
#define FC_READ_INPUT_REGISTERS     0x04
#define FC_WRITE_SINGLE_COIL        0x05
#define FC_WRITE_SINGLE_REGISTER    0x06
#define FC_WRITE_MULTIPLE_COILS     0x0f
#define FC_WRITE_MULTIPLE_REGISTERS 0x10

#endif /* __FUNCTION_CODE_H__ */
